### ISSUE TITLE
Plugin adds a permanent TSC status

### ISSUE THREAD

**Issue by oblitum** [fannheyward/coc-styled-components#1]
Plugin adds a permanent TSC to status, even when not editing typescript.

**Comment by fannheyward** [comment]
TSC is added by coc-tsserver, looks like tsserver is activated.

**Comment by oblitum** [comment]
Yeah but, it's happening now simply by opening nvim, even without any file. Isn't that a bug?

**Comment by fannheyward** [comment]
Reproduced it.

**Comment by fannheyward** [comment]
Fixed on 0.1.1, thanks for your feedback.
