### ISSUE TITLE
not working properly on windows

### ISSUE THREAD

**Issue by onichandame** [fannheyward/coc-styled-components#39]
# problem
auto-completion of ``styled.div`/* css here. Auto-Completion! */` `` is working perfectly on Linux. But not working nicely on Windows.

on Windows, when `styled-components.tags` is set to `["styled"]`, auto-completion only works in ``styled` ` `` but not ``styled.div` ` ``.

When `styled-components.tags` is set to `["styled.div"]`, auto-completion works in ``styled.div` ` `` but not in any other styled components.

# diagnostic message
N/A

# environment
- **OS:** Windows 10
- **nvim:** v0.4.3 with python 3.6 and node 13.9
- **coc:** latest
- **coc-styled-components:** latest

**Comment by fannheyward** [comment]
Can you test VSCode + [vscode-styled-components](https://marketplace.visualstudio.com/items?itemName=jpoissonnier.vscode-styled-components), does it work as your expect?

**Comment by onichandame** [comment]
currently I do not have access to a windows machine with vscode installed. will test it a couple of hours later.

**Comment by onichandame** [comment]
@fannheyward With a fresh installed vscode and vscode-styled-components, auto-completion works as expected.

Basically I downloaded and installed vscode, then install vscode-styled-components within vscode. Then open the project without any modification and try the auto-completion. it works.

**Comment by fannheyward** [comment]
Thank you for your test.

**Comment by onichandame** [comment]
@fannheyward I am trying to solve the issue. But I am new to the dev of coc extensions. Could you please tell me where the auto-completion logic is coded? I only found the configuration logic in the `activate` function.

**Comment by fannheyward** [comment]
This extension just adds typescript-styled-plugin to work with coc-tsserver. Maybe you need checkout coc-tsserver.

**Comment by onichandame** [comment]
> This extension just adds typescript-styled-plugin to work with coc-tsserver. Maybe you need checkout coc-tsserver.

thx. will take a look.

**Comment by onichandame** [comment]
After some search, I think a workaround is found. refer to [this issue](https://github.com/neoclide/coc.nvim/issues/660).

By setting `"suggest.timeout": 4000` everything works fine.

My guess would be that when a component that exactly matches `styled-components.tags`, coc figures it out quickly. But when it sees `styled.<component>` some extra time is required to resolve the component. Hence a short timeout prevents the suggestion list to be filled.
