### ISSUE TITLE
Can't get it to work

### ISSUE THREAD

**Issue by hoschi** [fannheyward/coc-styled-components#68]
![2020-09-06-184205_793x505_scrot](https://user-images.githubusercontent.com/163128/92330643-b8768580-f070-11ea-8701-2e6e0362700a.png)

In my opinion it should complete `disp` to `display`, or do I miss something here? I tried different projects, but none seems to work. Also I don't see anything in `CocDiagnostics` or coc log.

**Comment by fannheyward** [comment]
This extension needs https://styled-components.com to work.

**Comment by hoschi** [comment]
ok, thanks
