### ISSUE TITLE
createGlobalStyle

### ISSUE THREAD

**Issue by renanbrayner** [fannheyward/coc-styled-components#69]
is there any way to make this extension work with the createGlobalStyle functionality of styled-components or is this feature does not exists yet?

**Comment by yvesnrb** [comment]
You can add this to your CocConfig:
```json
{
  "styled-components.tags": [
    "styled",
    "css",
    "sty",
    "createGlobalStyle"
  ]
}
```

By default this plugin will only turn on inside of a template tag named styled, css or sty. Including createGlobalStyle into the array enables it there, too.
@fannheyward should this be a part of the default behaviour? I can create a pull request if necessary.

**Comment by fannheyward** [comment]
@yvesnrb PR is welcome.

**Comment by yvesnrb** [comment]
#79 This should work
