### ISSUE TITLE
No syntax highlighting for styled-components strings

### ISSUE THREAD

**Issue by ashishbinu** [fannheyward/coc-styled-components#92]
The css string in styled-components are of same color .There is no syntax highlighting of css in it.

![image](https://user-images.githubusercontent.com/56691622/106613630-6b033380-6590-11eb-9e07-2eea9023abe6.png)

Is there a way to enable it?

**Comment by hemedani** [comment]
yes did not highlight on typescript file also

**Comment by fannheyward** [comment]
Yes, coc-styled-components does nothing about highlight.
